[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
my_project = "5EhLWntoYBe6pb7drV4yq4ne1BfJTLK6EnFAG4kebQh2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/seyit/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
